cleanups

diff --git a/mxcolr b/mxcolr
--- a/mxcolr
+++ b/mxcolr
@@ -3,8 +3,8 @@
 ### FLAGS ##############################
 set -o noclobber # Avoid overlay files
 set -o errexit   # Avoid cascading errors
-set -o pipefail  # Unveils hidden failures
-set -o nounset   # Exposes unset variables
+set -o pipefail  # Unveil hidden failures
+set -o nounset   # Expose unset variables
 set -o errtrace  # Trace error LINENO
 
 trap 'echo Error at $LINENO' ERR
@@ -13,6 +13,12 @@ trap 'echo Error at $LINENO' ERR
 if ! command -v pastel 2>&1 /dev/null; then
   echo "pastel not found."
   echo " ==> https://github.com/sharkdp/pastel#installation"
+  exit 1
+fi
+
+if ! command -v bc 2>&1 /dev/null; then
+  echo "bc not found."
+  echo " ==> https://www.gnu.org/software/bc"
   exit 1
 fi
 
